namespace Instinct.Core.Enums;

public enum DamageUniversalType {
    Recontained,
    Warhead,
    Scp049,
    Unknown,
    Asphyxiated,
    Bleeding,
    Falldown,
    PocketDecay,
    Decontamination,
    Poisoned,
    Scp207,
    SeveredHands,
    MicroHid,
    Tesla,
    Explosion,
    Scp096,
    Scp173,
    Scp939Lunge,
    Zombie,
    BulletWounds,
    Crushed,
    UsedAs106Bait,
    FriendlyFireDetector,
    Hypothermia,
    CardiacArrest,
    Scp939Other,
    Scp3114Slap,
    MarshmallowMan,
    Scp1344,
    Scp1507Peck,
    Scp127Bullets,
    None = 255,
}