namespace Instinct.Core.Enums;

public enum EffectType {
    None,
    AmnesiaItems,
    AmnesiaVision,
    Asphyxiated,
    Bleeding,
    Blinded,
    Burned,
    Concussed,
    Corroding,
    Deafened,
    Decontaminating,
    Disabled,
    Ensnared,
    Exhausted,
    Flashed,
    Hemorrhage,
    Invigorated,
    BodyshotReduction,
    Poisoned,
    Scp207,
    Invisible,
    SinkHole,
    DamageReduction,
    MovementBoost,
    RainbowTaste,
    SeveredHands,
    Stained,
    Vitality,
    Hypothermia,
    Scp1853,
    CardiacArrest,
    InsufficientLighting,
    SoundtrackMute,
    SpawnProtected,
    Traumatized,
    AntiScp207,
    Scanned,
    PocketCorroding,
    SilentWalk,
    [Obsolete("Not functional in-game")] Marshmallow,
    Strangled,
    Ghostly,
    FogControl,
    Slowness,
    Scp1344,
    SeveredEyes,
    PitDeath,
    Blurred,
    [Obsolete("Only availaible for Christmas and AprilFools.")] BecomingFlamingo,
    [Obsolete("Only availaible for Christmas and AprilFools.")] Scp559,
    [Obsolete("Only availaible for Christmas and AprilFools.")] Scp956Target,
    [Obsolete("Only availaible for Christmas and AprilFools.")] Snowed,
    Scp1344Detected,
    Scp1576,
    Lightweight,
    HeavyFooted,
    Fade,
}